export const ActionTypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    FETCH_PRODUCTS:"FETCH_PRODUCTS",
    ADD_CART:"ADD_CART",
    SELECTED_PRODUCT:"SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT"
}